/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Input-Scope.h
 #	source generated by 4D Plugin Wizard
 #	Project : Input Scope
 #	author : miyako
 #	2019/07/24
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_INPUT_SCOPE_H
#define PLUGIN_INPUT_SCOPE_H

#include "4DPluginAPI.h"

#pragma mark -

void Set_input_scope(PA_PluginParameters params);

#endif /* PLUGIN_INPUT_SCOPE_H */
