/* --------------------------------------------------------------------------------
 #
 #  4DPlugin-Input-Scope.cpp
 #	source generated by 4D Plugin Wizard
 #	Project : Input Scope
 #	author : miyako
 #	2019/07/24
 #  
 # --------------------------------------------------------------------------------*/

#include "4DPlugin-Input-Scope.h"

#pragma mark -

#if VERSIONWIN
#include "windows.h"
#include "inputscope.h"
decltype(SetInputScope)*setInputScope = NULL;
HMODULE hMSCTF = NULL;
#endif

void PluginMain(PA_long32 selector, PA_PluginParameters params) {
    
	try
	{
        switch(selector)
        {
            case kInitPlugin:
            case kServerInitPlugin:
#if VERSIONWIN
                hMSCTF = LoadLibrary(TEXT("msctf.dll"));
                setInputScope = (decltype(SetInputScope)*)GetProcAddress(hMSCTF, "SetInputScope");
#endif
            break;
            
            case kDeinitPlugin:
#if VERSIONWIN
            if(hMSCTF)
            {
                FreeLibrary(hMSCTF);
                hMSCTF = NULL;
            }
#endif
            break;
            
			// --- Input Scope
            
			case 1 :
				Set_input_scope(params);
				break;

        }

	}
	catch(...)
	{

	}
}

#pragma mark -

void Set_input_scope(PA_PluginParameters params) {
    
#if VERSIONWIN

	InputScope p1 = (InputScope)PA_GetLongParameter(params, 1);
	HRESULT res = 0;

    if (setInputScope)
    {
		res = setInputScope(GetFocus(), p1);
    }

	PA_ReturnLong(params, res);
#endif
}

